In [1]:
import pandas as pd
import numpy as np

In [2]:
# A numpy array
arr = np.random.randn(4) # random values from std normal distribution
print(type(arr))
print(arr, "\n")

# A pandas series made from the previous array
s = pd.Series(arr)
print(type(s))
print(s)

<class 'numpy.ndarray'>
[ 0.026858   -0.10752792  0.47393901 -0.55422303]

<class 'pandas.core.series.Series'>
0    0.026858
1   -0.107528
2    0.473939
3   -0.554223
dtype: float64

s = pd.Series(data, index=index) creates pandas series

In [3]:
# A series from a numpy array (list of bojects)
pd.Series(np.arange(3), index=[2023, 2024, 2025])

2023    0
2024    1
2025    2
dtype: int64

In [6]:
# A series from a list of strings with default index
pd.Series(['EDS 220', 'EDS 222', 'EDS 223', 'EDS 242'])

0    EDS 220
1    EDS 222
2    EDS 223
3    EDS 242
dtype: object

In [7]:
# Construct dictionary
d = {'key_0':2, 'key_1':'3', 'key_2':5}

# Initialize series using a dictionary
pd.Series(d)

key_0    2
key_1    3
key_2    5
dtype: object

In [ ]:
# Series from a single float number with an index given by a list of strings
pd.Series(3.0, index = ['A', 'B', 'C'])

In [12]:
# Define a series
s = pd.Series([98,73,65],index=['Andrea', 'Beth', 'Carolina'])

# Divide each element in series by 10
print(s/10, '\n')

# Take the exponential of each element in series
print(np.exp(s), '\n')

# Original series is unchanged
print(s)

Andrea      9.8
Beth        7.3
Carolina    6.5
dtype: float64

Andrea      3.637971e+42
Beth        5.052394e+31
Carolina    1.694889e+28
dtype: float64

Andrea      98
Beth        73
Carolina    65
dtype: int64

In [11]:
s > 70

Andrea       True
Beth         True
Carolina    False
dtype: bool

In [13]:
# Series with NAs in it
s = pd.Series([1, 2, np.nan, 4, np.nan])
s

0    1.0
1    2.0
2    NaN
3    4.0
4    NaN
dtype: float64

In [14]:
# Check if series has NAs
s.hasnans

True

In [15]:
# Which elements in the series are NAs
s.isna()

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [2]:
s = pd.Series([4, -999, -999, 17], index=['A','B','C','D'])
s

A      4
B   -999
C   -999
D     17
dtype: int64

In [3]:
print(s.mask(s==-999))

A     4.0
B     NaN
C     NaN
D    17.0
dtype: float64

In [4]:
# Initialize dictionary with columns' data 
d = {'col_name_1' : pd.Series(np.arange(3)),
     'col_name_2' : pd.Series([3.1, 3.2, 3.3])
     }

# Create data frame
df = pd.DataFrame(d)
df

   col_name_1  col_name_2
0           0         3.1
1           1         3.2
2           2         3.3

In [29]:
# Change index
df.index = ['a','b','c']
df

   col_name_1  col_name_2
a           0         3.1
b           1         3.2
c           2         3.3

In [34]:
# Rename columns
df.columns = ['C1','C2']
df

   C1   C2
a   0  3.1
b   1  3.2
c   2  3.3